apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: molops
resources:
  - namespace.yaml
  - configmap.yaml
  - api-deployment.yaml
  - mlflow-deployment.yaml
  - hpa.yaml
images:
  - name: lyhamsea/molops
    newTag: latest
