apiVersion: v1
kind: Secret
metadata:
  name: molops-secrets
  namespace: molops
type: Opaque
stringData:
  MOLOPS_SECRET_KEY: "Iwillreplace this with a real secret key"
  GF_SECURITY_ADMIN_USER: "admin"
  GF_SECURITY_ADMIN_PASSWORD: "Iwillreplace this with a real password"